version: '3'
services:
  neo4j:
    image: neo4j:4.4.10-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_logs_query_enabled=true
      - NEO4J_dbms_logs_query_time__logging__enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - "./volumes/neo4j/data:/data"
      - "./volumes/neo4j/plugins:/plugins"
  api:
    build: ./api
    ports:
      - 4000:4000
    links:
      - neo4j
    depends_on:
      - neo4j
    environment:
      - DEBUG=@neo4j/graphql:*
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4000
