enum Seniority {
    JUNIOR
    REGULAR
    SENIOR
}

enum ExperienceType {
  DEFAULT
  PROJECT
  EDUCATION
  COURSE
  HOBBY
}

type Person {
  id: ID! @id @unique
  name: String!
  surname: String!
  bio: String
  birthday: Date
  location: Point
  seniority: Seniority @coalesce(value: REGULAR)
  skills: [Skill!]! @relationship(type: "HAS_SKILL", direction: OUT)
  roles: [Role!]! @relationship(type: "HAS_ROLE", direction: OUT)
  rates: [Rate!]! @relationship(type: "HAS_RATE", direction: OUT)
  projects: [Project!]! @relationship(type: "HAS_PROJECT", direction: OUT)
  departments: [Department!]! @relationship(type: "HAS_DEPARTMENT", direction: OUT)
  experiences: [Experience!]! @relationship(type: "HAS_EXPERIENCE", direction: OUT)
}

type Experience {
  id: ID! @id @unique
  type: ExperienceType! @coalesce(value: DEFAULT)
  person: Person @relationship(type: "HAS_EXPERIENCE", direction: IN)
  name: String
  role: String
  institution: String
  description: String
  skills: [Skill!]! @relationship(type: "USED_SKILL", direction: OUT)
  startedFrom: Date!
  gainedAt: Date
}

union SkillChild = Skill | SkillGroup

type SkillGroup {
  id: ID! @id @unique
  name: String!
  children: [SkillChild!]! @relationship(type: "BELONGS_TO", direction: IN)
  parents: [SkillGroup!]! @relationship(type: "BELONGS_TO", direction: OUT)
}

type Skill {
  id: ID! @id @unique
  name: String!
  groups: [SkillGroup!]! @cypher(statement: """
    MATCH (this)-[:BELONGS_TO]->+(sg:SkillGroup) RETURN sg
  """, columnName: "sg")
  persons: [Person!]! @relationship(type: "HAS_SKILL", direction: IN)
  experiences: [Experience!]! @relationship(type: "USED_SKILL", direction: IN)
  recommendedFor(projectId: String!): Boolean! @cypher(statement: """
    MATCH (this)
    RETURN exists((:Project {id: $projectId})-[:NEED_SKILL]->(this)) as exists
  """, columnName: "exists")
}

type Role {
  id: ID! @id @unique
  name: String!
}

type Project {
  id: ID! @id @unique
  name: String!
  skills: [Skill!]! @relationship(type: "NEED_SKILL", direction:OUT)
  persons: [Person!]! @relationship(type: "HAS_PROJECT", direction: IN)
  startedFrom: Date!
  duration: Duration!
}

type Department {
  id: ID! @id @unique
  name: String!
  manager: Person @relationship(type: "MANAGED_BY", direction: OUT)
  persons: [Person!]! @relationship(type: "HAS_DEPARTMENT", direction: IN)
}

type Rate {
  id: ID! @id @unique
  value: Float!
  validFrom: Date!
  person: Person! @relationship(type: "HAS_RATE", direction: IN)
}

type Query {
  findSkill(where: SkillWhere): [Skill!]! @cypher(statement: """MATCH (s:Skill) WHERE toUpper(s.name) = toUpper($where.name) RETURN s""", columnName: """s""")
}

type PersonsToProject {
 people: [PersonWithScore] @cypher(statement: """
        MATCH (p:Person)-[:HAS_SKILL]->(skill:Skill)<-[:NEED_SKILL]-(pr:Project)
        RETURN p,COUNT(*) AS score ORDER BY score DESC
    """, columnName: """p""")
}

type Score {
  score: Int
}

union PersonWithScore = Person | Score

type QueryP {
    people: [Person]
        @cypher(
            statement: """
            MATCH (p:Person)
            RETURN p
            """, columnName: """person"""
        )
}
