fragment _commonExperience on Experience {
  gainedAt
  startedFrom
  description
  skills {
    name
  }
}

query _CVQuery {
  people {
    name
    surname
    seniority
    bio
    roles {
      name
    }
    languages: skills(where: {groups:  {
      id: "Languages"
    }}) {
      name
    }
    skills(where: {groups_SOME:  {
      id: "Technologies"
    }}) {
      name
      groups {
        name
      }
      recommendedFor(projectId: "ProjectCV")
    }
    experience: experiences(where: {type: DEFAULT}){
      ..._commonExperience
      role
      institution
    }
    projects: experiences(where: {type: PROJECT}){
      ..._commonExperience
      name
      role
    }
    education: experiences(where: {type: EDUCATION}){
      ..._commonExperience
      name
      institution
    }
    courses: experiences(where: {type: COURSE}){
      ..._commonExperience
      name
      institution
    }
    hobby: experiences(where: {type: HOBBY}){
      name
    }
  }
}
